# This compose fragment describes development environment
# modifications to the original compose file.
version: "3"
services:
  compute-optimal-location-service:
    env_file:
      - ./env/local/local.env
      - ./env/local/secrets.env
    build:
      context: .
      dockerfile: ./env/Dockerfile
    ports:
      - "4010:4010"